import styled from "styled-components";
import WeaponBox from "./WeaponBox";

import { IWeaponData, WEAPON_SLOT_LIST } from "../../../../@types/maple/WeaponTypes";
import { voidStrToCamelCase } from "../../../../hooks/commonUtils";

const StyledBox = styled.div`
  width: 320px;
  box-sizing: border-box;
  padding: 8px;
  background-color: #3d454d;
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
`;

const DUMMY_WEAPONS: IWeaponData[] = [
  {
    item_equipment_part: "모자",
    item_equipment_slot: "모자",
    item_name: "카오스 반반 투구",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPCIAMB.png",
    item_description: null,
    item_shape_name: "자쿰의 투구",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPCJELG.png",
    item_gender: null,
    item_total_option: {
      str: "126",
      dex: "126",
      int: "126",
      luk: "126",
      max_hp: "255",
      max_mp: "0",
      attack_power: "108",
      magic_power: "79",
      armor: "898",
      speed: "5",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "4",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "23",
      dex: "23",
      int: "23",
      luk: "23",
      max_hp: "0",
      max_mp: "0",
      attack_power: "1",
      magic_power: "1",
      armor: "300",
      speed: "5",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 140,
    },
    potential_option_grade: "레전드리",
    additional_potential_option_grade: "유니크",
    potential_option_1: "LUK : +12%",
    potential_option_2: "올스탯 : +6%",
    potential_option_3: "LUK : +9%",
    additional_potential_option_1: "LUK : +6%",
    additional_potential_option_2: "LUK : +4%",
    additional_potential_option_3: "올스탯 : +2%",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "2",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "4",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "11",
    cuttable_count: "4",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "27",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "22",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "103",
      dex: "103",
      int: "103",
      luk: "103",
      max_hp: "255",
      max_mp: "0",
      attack_power: "78",
      magic_power: "78",
      armor: "598",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "상의",
    item_equipment_slot: "상의",
    item_name: "이글아이 어새신셔츠",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPGJFLG.png",
    item_description: null,
    item_shape_name: "이글아이 어새신셔츠",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPGJFLG.png",
    item_gender: null,
    item_total_option: {
      str: "24",
      dex: "143",
      int: "20",
      luk: "199",
      max_hp: "325",
      max_mp: "0",
      attack_power: "40",
      magic_power: "30",
      armor: "354",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "5",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "0",
      dex: "30",
      int: "0",
      luk: "30",
      max_hp: "0",
      max_mp: "0",
      attack_power: "2",
      magic_power: "0",
      armor: "135",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "5",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 150,
    },
    potential_option_grade: "에픽",
    additional_potential_option_grade: "에픽",
    potential_option_1: "LUK : +6%",
    potential_option_2: "최대 HP : +120",
    potential_option_3: "최대 HP : +120",
    additional_potential_option_1: "올스탯 : +2%",
    additional_potential_option_2: "공격력 : +10",
    additional_potential_option_3: "INT : +4%",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "24",
      dex: "40",
      int: "20",
      luk: "92",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "6",
    cuttable_count: "10",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "1",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "4",
      max_hp: "70",
      max_mp: "0",
      attack_power: "8",
      magic_power: "0",
      armor: "5",
      speed: "0",
      jump: "0",
    },
    starforce: "18",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "73",
      int: "0",
      luk: "73",
      max_hp: "255",
      max_mp: "0",
      attack_power: "30",
      magic_power: "30",
      armor: "214",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "하의",
    item_equipment_slot: "하의",
    item_name: "트릭스터 어새신팬츠",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPEJGIJ.png",
    item_description: null,
    item_shape_name: "트릭스터 어새신팬츠",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPEJGIJ.png",
    item_gender: null,
    item_total_option: {
      str: "0",
      dex: "168",
      int: "0",
      luk: "165",
      max_hp: "465",
      max_mp: "0",
      attack_power: "22",
      magic_power: "19",
      armor: "372",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "5",
      all_stat: "5",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "0",
      dex: "30",
      int: "0",
      luk: "30",
      max_hp: "0",
      max_mp: "0",
      attack_power: "2",
      magic_power: "0",
      armor: "135",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "5",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 150,
    },
    potential_option_grade: "에픽",
    additional_potential_option_grade: "레어",
    potential_option_1: "LUK : +6%",
    potential_option_2: "LUK : +3%",
    potential_option_3: "LUK : +3%",
    additional_potential_option_1: "공격력 : +10",
    additional_potential_option_2: "점프력 : +4",
    additional_potential_option_3: null,
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "76",
      int: "0",
      luk: "52",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "5",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "7",
    cuttable_count: "7",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "21",
      max_hp: "210",
      max_mp: "0",
      attack_power: "1",
      magic_power: "0",
      armor: "21",
      speed: "0",
      jump: "0",
    },
    starforce: "17",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "62",
      int: "0",
      luk: "62",
      max_hp: "255",
      max_mp: "0",
      attack_power: "19",
      magic_power: "19",
      armor: "216",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "망토",
    item_equipment_slot: "망토",
    item_name: "아케인셰이드 시프케이프",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOCJOKC.png",
    item_description: null,
    item_shape_name: "아케인셰이드 시프케이프",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOCJOKC.png",
    item_gender: null,
    item_total_option: {
      str: "35",
      dex: "66",
      int: "35",
      luk: "177",
      max_hp: "1140",
      max_mp: "3600",
      attack_power: "7",
      magic_power: "6",
      armor: "959",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "6",
      damage: "0",
      equipment_level_decrease: 25,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "35",
      dex: "35",
      int: "35",
      luk: "35",
      max_hp: "0",
      max_mp: "0",
      attack_power: "6",
      magic_power: "6",
      armor: "450",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 200,
    },
    potential_option_grade: "유니크",
    additional_potential_option_grade: "레어",
    potential_option_1: "LUK : +9%",
    potential_option_2: "LUK : +6%",
    potential_option_3: "DEX : +6%",
    additional_potential_option_1: "DEX : +2%",
    additional_potential_option_2: "공격력 : +3",
    additional_potential_option_3: "STR : +6",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "55",
      max_hp: "0",
      max_mp: "3600",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "6",
      equipment_level_decrease: 25,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "8",
    cuttable_count: "9",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "56",
      max_hp: "960",
      max_mp: "0",
      attack_power: "1",
      magic_power: "0",
      armor: "80",
      speed: "0",
      jump: "0",
    },
    starforce: "12",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "31",
      int: "0",
      luk: "31",
      max_hp: "180",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "429",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "장갑",
    item_equipment_slot: "장갑",
    item_name: "아케인셰이드 시프글러브",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPKJBHJ.png",
    item_description: null,
    item_shape_name: "아케인셰이드 시프글러브",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPKJBHJ.png",
    item_gender: null,
    item_total_option: {
      str: "36",
      dex: "71",
      int: "0",
      luk: "107",
      max_hp: "0",
      max_mp: "2400",
      attack_power: "37",
      magic_power: "0",
      armor: "500",
      speed: "0",
      jump: "5",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "0",
      dex: "40",
      int: "0",
      luk: "40",
      max_hp: "0",
      max_mp: "0",
      attack_power: "9",
      magic_power: "0",
      armor: "250",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 200,
    },
    potential_option_grade: "레전드리",
    additional_potential_option_grade: "레어",
    potential_option_1: "크리티컬 데미지 : +8%",
    potential_option_2: "피격 시 5% 확률로 데미지의 20% 무시",
    potential_option_3: "STR : +9%",
    additional_potential_option_1: "LUK : +2%",
    additional_potential_option_2: "공격력 : +3",
    additional_potential_option_3: "공격력 : +3",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "36",
      dex: "0",
      int: "0",
      luk: "36",
      max_hp: "0",
      max_mp: "2400",
      attack_power: "0",
      magic_power: "0",
      armor: "44",
      speed: "0",
      jump: "5",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "6",
    cuttable_count: "10",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "1",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "24",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "12",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "31",
      int: "0",
      luk: "31",
      max_hp: "0",
      max_mp: "0",
      attack_power: "4",
      magic_power: "0",
      armor: "206",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "신발",
    item_equipment_slot: "신발",
    item_name: "아케인셰이드 시프슈즈",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPFIGIA.png",
    item_description: null,
    item_shape_name: "아케인셰이드 시프슈즈",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPFIGIA.png",
    item_gender: null,
    item_total_option: {
      str: "30",
      dex: "71",
      int: "30",
      luk: "186",
      max_hp: "840",
      max_mp: "0",
      attack_power: "10",
      magic_power: "4",
      armor: "582",
      speed: "22",
      jump: "19",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "5",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "0",
      dex: "40",
      int: "0",
      luk: "40",
      max_hp: "0",
      max_mp: "0",
      attack_power: "9",
      magic_power: "0",
      armor: "250",
      speed: "10",
      jump: "7",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 200,
    },
    potential_option_grade: "유니크",
    additional_potential_option_grade: "레어",
    potential_option_1: "LUK : +9%",
    potential_option_2: "LUK : +6%",
    potential_option_3: "INT : +6%",
    additional_potential_option_1: "공격력 : +10",
    additional_potential_option_2: "INT : +6",
    additional_potential_option_3: "STR : +6",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "30",
      dex: "0",
      int: "30",
      luk: "66",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "4",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "5",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "7",
    cuttable_count: "10",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "1",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "49",
      max_hp: "840",
      max_mp: "0",
      attack_power: "1",
      magic_power: "0",
      armor: "70",
      speed: "0",
      jump: "0",
    },
    starforce: "12",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "31",
      int: "0",
      luk: "31",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "262",
      speed: "12",
      jump: "12",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "반지",
    item_equipment_slot: "반지1",
    item_name: "어웨이크 링",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEODPEPJ.png",
    item_description:
      "각성의 산에서 얻을 수 있는 특별한 능력의 반지이다.\n어웨이크 링 전용 강화 주문서만 사용 가능\n잠재능력 및 에디셔널 잠재능력 부여 가능",
    item_shape_name: "어웨이크 링",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEODPEPJ.png",
    item_gender: null,
    item_total_option: {
      str: "40",
      dex: "40",
      int: "40",
      luk: "40",
      max_hp: "4000",
      max_mp: "4000",
      attack_power: "25",
      magic_power: "25",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      max_hp: "1000",
      max_mp: "1000",
      attack_power: "10",
      magic_power: "10",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 120,
    },
    potential_option_grade: "레전드리",
    additional_potential_option_grade: "레어",
    potential_option_1: "아이템 드롭률 : +20%",
    potential_option_2: "LUK : +9%",
    potential_option_3: "LUK : +9%",
    additional_potential_option_1: "공격력 : +10",
    additional_potential_option_2: "점프력 : +4",
    additional_potential_option_3: "LUK : +6",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "3",
    cuttable_count: "255",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "30",
      dex: "30",
      int: "30",
      luk: "30",
      max_hp: "3000",
      max_mp: "3000",
      attack_power: "15",
      magic_power: "15",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "0",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "반지",
    item_equipment_slot: "반지2",
    item_name: "실버블라썸 링",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEODIGKI.png",
    item_description: null,
    item_shape_name: "실버블라썸 링",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEODIGKI.png",
    item_gender: null,
    item_total_option: {
      str: "35",
      dex: "40",
      int: "32",
      luk: "33",
      max_hp: "130",
      max_mp: "0",
      attack_power: "6",
      magic_power: "4",
      armor: "11",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      max_hp: "0",
      max_mp: "0",
      attack_power: "2",
      magic_power: "2",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 110,
    },
    potential_option_grade: "에픽",
    additional_potential_option_grade: null,
    potential_option_1: "LUK : +6%",
    potential_option_2: "LUK : +3%",
    potential_option_3: "최대 MP : +3%",
    additional_potential_option_1: null,
    additional_potential_option_2: null,
    additional_potential_option_3: null,
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "2",
    cuttable_count: "10",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "1",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "5",
      dex: "10",
      int: "2",
      luk: "3",
      max_hp: "0",
      max_mp: "0",
      attack_power: "4",
      magic_power: "2",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "10",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "25",
      dex: "25",
      int: "25",
      luk: "25",
      max_hp: "130",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "11",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "반지",
    item_equipment_slot: "반지3",
    item_name: "고귀한 이피아의 반지",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEODIFGD.png",
    item_description: null,
    item_shape_name: "고귀한 이피아의 반지",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEODIFGD.png",
    item_gender: null,
    item_total_option: {
      str: "50",
      dex: "54",
      int: "50",
      luk: "55",
      max_hp: "475",
      max_mp: "250",
      attack_power: "10",
      magic_power: "11",
      armor: "16",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      max_hp: "200",
      max_mp: "200",
      attack_power: "2",
      magic_power: "2",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 120,
    },
    potential_option_grade: "에픽",
    additional_potential_option_grade: "레어",
    potential_option_1: "LUK : +6%",
    potential_option_2: "LUK : +6%",
    potential_option_3: "올스탯 : +5",
    additional_potential_option_1: "공격력 : +10",
    additional_potential_option_2: "이동속도 : +4",
    additional_potential_option_3: "LUK : +6",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "3",
    cuttable_count: "9",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "5",
      dex: "9",
      int: "5",
      luk: "10",
      max_hp: "20",
      max_mp: "50",
      attack_power: "8",
      magic_power: "9",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "15",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "40",
      dex: "40",
      int: "40",
      luk: "40",
      max_hp: "255",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "16",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "반지",
    item_equipment_slot: "반지4",
    item_name: "이터널 플레임 링",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEODPEMF.png",
    item_description: "꺼지지 않는 불꽃의 힘이 깃든 특별한 반지이다.",
    item_shape_name: "이터널 플레임 링",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEODPEMF.png",
    item_gender: null,
    item_total_option: {
      str: "40",
      dex: "40",
      int: "40",
      luk: "40",
      max_hp: "4000",
      max_mp: "4000",
      attack_power: "25",
      magic_power: "25",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "40",
      dex: "40",
      int: "40",
      luk: "40",
      max_hp: "4000",
      max_mp: "4000",
      attack_power: "25",
      magic_power: "25",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 120,
    },
    potential_option_grade: "레전드리",
    additional_potential_option_grade: "레어",
    potential_option_1: "LUK : +12%",
    potential_option_2: "최대 MP : +9%",
    potential_option_3: "최대 HP : +9%",
    additional_potential_option_1: "최대 MP : +100",
    additional_potential_option_2: "공격력 : +10",
    additional_potential_option_3: "방어력 : +60",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "0",
    cuttable_count: "255",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "0",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "펜던트",
    item_equipment_slot: "펜던트",
    item_name: "그리드 펜던트",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOAJFPI.png",
    item_description: "착용자의 탐욕을 극대화하여 장비 드롭률을 20% 증가시킨다.",
    item_shape_name: "그리드 펜던트",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOAJFPI.png",
    item_gender: null,
    item_total_option: {
      str: "3",
      dex: "3",
      int: "3",
      luk: "3",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "100",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "3",
      dex: "3",
      int: "3",
      luk: "3",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "100",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 75,
    },
    potential_option_grade: null,
    additional_potential_option_grade: null,
    potential_option_1: null,
    potential_option_2: null,
    potential_option_3: null,
    additional_potential_option_1: null,
    additional_potential_option_2: null,
    additional_potential_option_3: null,
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "0",
    cuttable_count: "255",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "6",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "0",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "펜던트",
    item_equipment_slot: "펜던트2",
    item_name: "도미네이터 펜던트",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOAJEJE.png",
    item_description: "검은 마법사의 군단장 아카이럼이 지녔다고 알려진 전설의 목걸이",
    item_shape_name: "도미네이터 펜던트",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOAJEJE.png",
    item_gender: null,
    item_total_option: {
      str: "60",
      dex: "80",
      int: "80",
      luk: "125",
      max_hp: "255",
      max_mp: "0",
      attack_power: "8",
      magic_power: "3",
      armor: "219",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "5",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "10",
      max_mp_rate: "10",
    },
    item_base_option: {
      str: "20",
      dex: "20",
      int: "20",
      luk: "20",
      max_hp: "0",
      max_mp: "0",
      attack_power: "3",
      magic_power: "3",
      armor: "100",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 140,
    },
    potential_option_grade: "유니크",
    additional_potential_option_grade: null,
    potential_option_1: "LUK : +9%",
    potential_option_2: "LUK : +6%",
    potential_option_3: "크리티컬 확률 : +6%",
    additional_potential_option_1: null,
    additional_potential_option_2: null,
    additional_potential_option_3: null,
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "20",
      int: "20",
      luk: "40",
      max_hp: "0",
      max_mp: "0",
      attack_power: "5",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "5",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "5",
    cuttable_count: "255",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "25",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "15",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "40",
      dex: "40",
      int: "40",
      luk: "40",
      max_hp: "255",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "119",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "얼굴장식",
    item_equipment_slot: "얼굴장식",
    item_name: "응축된 힘의 결정석",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPDJDJJ.png",
    item_description: null,
    item_shape_name: "응축된 힘의 결정석",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPDJDJJ.png",
    item_gender: null,
    item_total_option: {
      str: "60",
      dex: "40",
      int: "30",
      luk: "66",
      max_hp: "0",
      max_mp: "0",
      attack_power: "5",
      magic_power: "5",
      armor: "170",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "5",
      damage: "0",
      equipment_level_decrease: 20,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      max_hp: "0",
      max_mp: "0",
      attack_power: "5",
      magic_power: "5",
      armor: "100",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 110,
    },
    potential_option_grade: "유니크",
    additional_potential_option_grade: "레어",
    potential_option_1: "LUK : +9%",
    potential_option_2: "LUK : +6%",
    potential_option_3: "LUK : +6%",
    additional_potential_option_1: "공격력 : +10",
    additional_potential_option_2: "방어력 : +55",
    additional_potential_option_3: "STR : +6",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "30",
      dex: "0",
      int: "0",
      luk: "36",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "5",
      equipment_level_decrease: 20,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "5",
    cuttable_count: "9",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "1",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "10",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "10",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "25",
      dex: "25",
      int: "25",
      luk: "25",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "70",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "눈장식",
    item_equipment_slot: "눈장식",
    item_name: "파풀라투스 마크",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPAJFJG.png",
    item_description: null,
    item_shape_name: "마력이 깃든 안대",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPAJFJJ.png",
    item_gender: null,
    item_total_option: {
      str: "75",
      dex: "75",
      int: "75",
      luk: "153",
      max_hp: "2100",
      max_mp: "1680",
      attack_power: "28",
      magic_power: "28",
      armor: "374",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "6",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "8",
      dex: "8",
      int: "8",
      luk: "8",
      max_hp: "0",
      max_mp: "0",
      attack_power: "1",
      magic_power: "1",
      armor: "150",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 145,
    },
    potential_option_grade: "에픽",
    additional_potential_option_grade: "레어",
    potential_option_1: "LUK : +6%",
    potential_option_2: "LUK : +6%",
    potential_option_3: "LUK : +3%",
    additional_potential_option_1: "공격력 : +10",
    additional_potential_option_2: "STR : +6",
    additional_potential_option_3: "최대 MP : +60",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "48",
      max_hp: "2100",
      max_mp: "1680",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "6",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "6",
    cuttable_count: "9",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "30",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "18",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "67",
      dex: "67",
      int: "67",
      luk: "67",
      max_hp: "0",
      max_mp: "0",
      attack_power: "27",
      magic_power: "27",
      armor: "224",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "귀고리",
    item_equipment_slot: "귀고리",
    item_name: "데아 시두스 이어링",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPBJFKA.png",
    item_description: null,
    item_shape_name: "데아 시두스 이어링",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEPBJFKA.png",
    item_gender: null,
    item_total_option: {
      str: "59",
      dex: "59",
      int: "83",
      luk: "141",
      max_hp: "0",
      max_mp: "0",
      attack_power: "19",
      magic_power: "17",
      armor: "127",
      speed: "0",
      jump: "4",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "6",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      max_hp: "0",
      max_mp: "0",
      attack_power: "2",
      magic_power: "2",
      armor: "50",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 130,
    },
    potential_option_grade: "유니크",
    additional_potential_option_grade: "에픽",
    potential_option_1: "올스탯 : +6%",
    potential_option_2: "LUK : +6%",
    potential_option_3: "LUK : +6%",
    additional_potential_option_1: "LUK : +4%",
    additional_potential_option_2: "이동속도 : +6",
    additional_potential_option_3: "STR : +10",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "24",
      luk: "52",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "4",
      boss_damage: "0",
      damage: "0",
      all_stat: "6",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "7",
    cuttable_count: "8",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "30",
      max_hp: "0",
      max_mp: "0",
      attack_power: "2",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "17",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "54",
      dex: "54",
      int: "54",
      luk: "54",
      max_hp: "0",
      max_mp: "0",
      attack_power: "15",
      magic_power: "15",
      armor: "77",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "어깨장식",
    item_equipment_slot: "어깨장식",
    item_name: "아케인셰이드 시프숄더",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOHJGHI.png",
    item_description: null,
    item_shape_name: "아케인셰이드 시프숄더",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOHJGHI.png",
    item_gender: null,
    item_total_option: {
      str: "37",
      dex: "78",
      int: "39",
      luk: "75",
      max_hp: "255",
      max_mp: "0",
      attack_power: "22",
      magic_power: "22",
      armor: "639",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "35",
      dex: "35",
      int: "35",
      luk: "35",
      max_hp: "0",
      max_mp: "0",
      attack_power: "20",
      magic_power: "20",
      armor: "300",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 200,
    },
    potential_option_grade: "레전드리",
    additional_potential_option_grade: "에픽",
    potential_option_1: "LUK : +12%",
    potential_option_2: "LUK : +9%",
    potential_option_3: "올스탯 : +6%",
    additional_potential_option_1: "공격력 : +11",
    additional_potential_option_2: "LUK : +2%",
    additional_potential_option_3: "최대 HP : +100",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "2",
    cuttable_count: "255",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "2",
      dex: "3",
      int: "4",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "2",
      magic_power: "2",
      armor: "3",
      speed: "0",
      jump: "0",
    },
    starforce: "15",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "40",
      int: "0",
      luk: "40",
      max_hp: "255",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "336",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "뱃지",
    item_equipment_slot: "뱃지",
    item_name: "크리스탈 웬투스 뱃지",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOKJHGG.png",
    item_description: null,
    item_shape_name: "크리스탈 웬투스 뱃지",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOKJHGG.png",
    item_gender: null,
    item_total_option: {
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      max_hp: "0",
      max_mp: "0",
      attack_power: "5",
      magic_power: "5",
      armor: "0",
      speed: "10",
      jump: "10",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      max_hp: "0",
      max_mp: "0",
      attack_power: "5",
      magic_power: "5",
      armor: "0",
      speed: "10",
      jump: "10",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 130,
    },
    potential_option_grade: null,
    additional_potential_option_grade: null,
    potential_option_1: null,
    potential_option_2: null,
    potential_option_3: null,
    additional_potential_option_1: null,
    additional_potential_option_2: null,
    additional_potential_option_3: null,
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "0",
    cuttable_count: "255",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "0",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "벨트",
    item_equipment_slot: "벨트",
    item_name: "분노한 자쿰의 벨트",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOBJFHH.png",
    item_description: null,
    item_shape_name: "분노한 자쿰의 벨트",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOBJFHH.png",
    item_gender: null,
    item_total_option: {
      str: "80",
      dex: "100",
      int: "80",
      luk: "109",
      max_hp: "405",
      max_mp: "2400",
      attack_power: "25",
      magic_power: "20",
      armor: "356",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "6",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "18",
      dex: "18",
      int: "18",
      luk: "18",
      max_hp: "150",
      max_mp: "150",
      attack_power: "1",
      magic_power: "1",
      armor: "150",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 150,
    },
    potential_option_grade: "에픽",
    additional_potential_option_grade: "에픽",
    potential_option_1: "LUK : +6%",
    potential_option_2: "STR : +12",
    potential_option_3: "INT : +12",
    additional_potential_option_1: "LUK : +14",
    additional_potential_option_2: "공격력 : +10",
    additional_potential_option_3: "올스탯 : +3",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "20",
      int: "0",
      luk: "20",
      max_hp: "0",
      max_mp: "2250",
      attack_power: "5",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "6",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "3",
    cuttable_count: "9",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "1",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "9",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "17",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "62",
      dex: "62",
      int: "62",
      luk: "62",
      max_hp: "255",
      max_mp: "0",
      attack_power: "19",
      magic_power: "19",
      armor: "206",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "훈장",
    item_equipment_slot: "훈장",
    item_name: "우르스 격파왕",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOGJPJI.png",
    item_description: "우르스를 10회 클리어 하면 획득할 수 있는 훈장이다.",
    item_shape_name: "우르스 격파왕",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOGJPJI.png",
    item_gender: null,
    item_total_option: {
      str: "7",
      dex: "7",
      int: "7",
      luk: "7",
      max_hp: "0",
      max_mp: "0",
      attack_power: "7",
      magic_power: "7",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "7",
      dex: "7",
      int: "7",
      luk: "7",
      max_hp: "0",
      max_mp: "0",
      attack_power: "7",
      magic_power: "7",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 100,
    },
    potential_option_grade: null,
    additional_potential_option_grade: null,
    potential_option_1: null,
    potential_option_2: null,
    potential_option_3: null,
    additional_potential_option_1: null,
    additional_potential_option_2: null,
    additional_potential_option_3: null,
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "0",
    cuttable_count: "255",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "0",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "아대",
    item_equipment_slot: "무기",
    item_name: "파프니르 리스크홀더",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KELFJFPF.png",
    item_description: null,
    item_shape_name: "메이플 칸데오",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KELFJHND.png",
    item_gender: null,
    item_total_option: {
      str: "0",
      dex: "157",
      int: "0",
      luk: "241",
      max_hp: "255",
      max_mp: "2955",
      attack_power: "333",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "42",
      ignore_monster_armor: "10",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "0",
      dex: "40",
      int: "0",
      luk: "40",
      max_hp: "0",
      max_mp: "0",
      attack_power: "86",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "30",
      ignore_monster_armor: "10",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 150,
    },
    potential_option_grade: "레전드리",
    additional_potential_option_grade: "레전드리",
    potential_option_1: "보스 몬스터 공격 시 데미지 : +40%",
    potential_option_2: "보스 몬스터 공격 시 데미지 : +30%",
    potential_option_3: "몬스터 방어율 무시 : +30%",
    additional_potential_option_1: "공격력 : +12%",
    additional_potential_option_2: "캐릭터 기준 9레벨 당 LUK : +1",
    additional_potential_option_3: "공격력 : +9%",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "48",
      max_hp: "0",
      max_mp: "2700",
      attack_power: "28",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "12",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "9",
    cuttable_count: "4",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: "위대한 매그너스의 소울 적용",
    soul_option: "공격력 : +3%",
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "36",
      max_hp: "0",
      max_mp: "0",
      attack_power: "81",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "22",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "117",
      int: "0",
      luk: "117",
      max_hp: "255",
      max_mp: "255",
      attack_power: "138",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "보석",
    item_equipment_slot: "보조무기",
    item_name: "에레브의 광휘",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEMHJOJD.png",
    item_description: null,
    item_shape_name: "에레브의 광휘",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEMHJOJD.png",
    item_gender: null,
    item_total_option: {
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      max_hp: "0",
      max_mp: "0",
      attack_power: "3",
      magic_power: "3",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      max_hp: "0",
      max_mp: "0",
      attack_power: "3",
      magic_power: "3",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 100,
    },
    potential_option_grade: "레전드리",
    additional_potential_option_grade: "레전드리",
    potential_option_1: "공격력 : +12%",
    potential_option_2: "보스 몬스터 공격 시 데미지 : +30%",
    potential_option_3: "공격력 : +9%",
    additional_potential_option_1: "공격력 : +12%",
    additional_potential_option_2: "공격 시 15% 확률로 85의 HP 회복",
    additional_potential_option_3: "공격력 : +9%",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "0",
    cuttable_count: "255",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "0",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "엠블렘",
    item_equipment_slot: "엠블렘",
    item_name: "골드 시그너스 엠블렘",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOLLPOA.png",
    item_description: null,
    item_shape_name: "골드 시그너스 엠블렘",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOLLPOA.png",
    item_gender: null,
    item_total_option: {
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      max_hp: "0",
      max_mp: "0",
      attack_power: "2",
      magic_power: "2",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "10",
      dex: "10",
      int: "10",
      luk: "10",
      max_hp: "0",
      max_mp: "0",
      attack_power: "2",
      magic_power: "2",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 100,
    },
    potential_option_grade: "레전드리",
    additional_potential_option_grade: "레전드리",
    potential_option_1: "몬스터 방어율 무시 : +35%",
    potential_option_2: "공격력 : +9%",
    potential_option_3: "공격력 : +9%",
    additional_potential_option_1: "몬스터 방어율 무시 : +5%",
    additional_potential_option_2: "STR : +9%",
    additional_potential_option_3: "데미지 : +9%",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "0",
    cuttable_count: "255",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "0",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "포켓 아이템",
    item_equipment_slot: "포켓 아이템",
    item_name: "핑크빛 성배",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOEJHME.png",
    item_description: null,
    item_shape_name: "핑크빛 성배",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEOEJHME.png",
    item_gender: null,
    item_total_option: {
      str: "25",
      dex: "25",
      int: "45",
      luk: "45",
      max_hp: "50",
      max_mp: "50",
      attack_power: "5",
      magic_power: "5",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "6",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "5",
      dex: "5",
      int: "5",
      luk: "5",
      max_hp: "50",
      max_mp: "50",
      attack_power: "5",
      magic_power: "5",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 140,
    },
    potential_option_grade: null,
    additional_potential_option_grade: null,
    potential_option_1: null,
    potential_option_2: null,
    potential_option_3: null,
    additional_potential_option_1: null,
    additional_potential_option_2: null,
    additional_potential_option_3: null,
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "20",
      dex: "20",
      int: "40",
      luk: "40",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "6",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "0",
    cuttable_count: "255",
    golden_hammer_flag: "미적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "0",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
  {
    item_equipment_part: "기계 심장",
    item_equipment_slot: "기계 심장",
    item_name: "페어리 하트",
    item_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEJFJHJI.png",
    item_description: null,
    item_shape_name: "페어리 하트",
    item_shape_icon: "https://open.api.nexon.com/static/maplestory/ItemIcon/KEJFJHJI.png",
    item_gender: null,
    item_total_option: {
      str: "19",
      dex: "19",
      int: "19",
      luk: "19",
      max_hp: "100",
      max_mp: "0",
      attack_power: "50",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      damage: "0",
      equipment_level_decrease: 0,
      max_hp_rate: "0",
      max_mp_rate: "0",
    },
    item_base_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "100",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      ignore_monster_armor: "0",
      all_stat: "0",
      max_hp_rate: "0",
      max_mp_rate: "0",
      base_equipment_level: 100,
    },
    potential_option_grade: "유니크",
    additional_potential_option_grade: "레어",
    potential_option_1: "LUK : +9%",
    potential_option_2: "LUK : +6%",
    potential_option_3: "최대 MP : +6%",
    additional_potential_option_1: "공격력 : +10",
    additional_potential_option_2: "LUK : +6",
    additional_potential_option_3: "최대 MP : +50",
    equipment_level_increase: 0,
    item_exceptional_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
    },
    item_add_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
      boss_damage: "0",
      damage: "0",
      all_stat: "0",
      equipment_level_decrease: 0,
    },
    growth_exp: 0,
    growth_level: 0,
    scroll_upgrade: "10",
    cuttable_count: "255",
    golden_hammer_flag: "적용",
    scroll_resilience_count: "0",
    scroll_upgradeable_count: "0",
    soul_name: null,
    soul_option: null,
    item_etc_option: {
      str: "0",
      dex: "0",
      int: "0",
      luk: "0",
      max_hp: "0",
      max_mp: "0",
      attack_power: "50",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    starforce: "8",
    starforce_scroll_flag: "미사용",
    item_starforce_option: {
      str: "19",
      dex: "19",
      int: "19",
      luk: "19",
      max_hp: "0",
      max_mp: "0",
      attack_power: "0",
      magic_power: "0",
      armor: "0",
      speed: "0",
      jump: "0",
    },
    special_ring_level: 0,
    date_expire: null,
  },
];

const CharacterWeapons = () => {
  const WEAPONS = new Map<string, IWeaponData>();

  DUMMY_WEAPONS.forEach((item: IWeaponData) => {
    const slot = voidStrToCamelCase(item.item_equipment_slot);
    if (WEAPON_SLOT_LIST.indexOf(slot) >= 0) {
      WEAPONS.set(slot, item);
    }
  });

  return (
    <StyledBox>
      {/* 첫 줄 */}
      <WeaponBox data={WEAPONS.get("반지4")} />
      <WeaponBox />
      <WeaponBox data={WEAPONS.get("모자")} />
      <WeaponBox />
      <WeaponBox data={WEAPONS.get("엠블렘")} />
      {/* 둘째 줄 */}
      <WeaponBox data={WEAPONS.get("반지3")} />
      <WeaponBox data={WEAPONS.get("펜던트")} />
      <WeaponBox data={WEAPONS.get("얼굴장식")} />
      <WeaponBox />
      <WeaponBox data={WEAPONS.get("뱃지")} />
      {/* 셋째 줄 */}
      <WeaponBox data={WEAPONS.get("반지2")} />
      <WeaponBox data={WEAPONS.get("펜던트2")} />
      <WeaponBox data={WEAPONS.get("눈장식")} />
      <WeaponBox data={WEAPONS.get("귀고리")} />
      <WeaponBox data={WEAPONS.get("훈장")} />
      {/* 넷째 줄 */}
      <WeaponBox data={WEAPONS.get("반지1")} />
      <WeaponBox data={WEAPONS.get("무기")} />
      <WeaponBox data={WEAPONS.get("상의")} />
      <WeaponBox data={WEAPONS.get("어깨장식")} />
      <WeaponBox data={WEAPONS.get("보조무기")} />
      {/* 다섯째 줄 */}
      <WeaponBox data={WEAPONS.get("포켓_아이템")} />
      <WeaponBox data={WEAPONS.get("벨트")} />
      <WeaponBox data={WEAPONS.get("하의")} />
      <WeaponBox data={WEAPONS.get("장갑")} />
      <WeaponBox data={WEAPONS.get("망토")} />
      {/* 여섯째 줄 */}
      <WeaponBox data={WEAPONS.get("모자")} />
      <WeaponBox />
      <WeaponBox data={WEAPONS.get("신발")} />
      <WeaponBox data={WEAPONS.get("모자")} />
      <WeaponBox data={WEAPONS.get("기계_심장")} />
    </StyledBox>
  );
};

export default CharacterWeapons;

